# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0NKeGFXbUd2Qk1IMHV2QXR4YjlwcVFJdjRHVnI2d082bURKVUpmY2JYUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVlJDR1NKUWNtWmg3cE5xNWR6SzM4bFB4VmFCRGxHSkUwSUhiQ2NRYmNRaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnQzNyZVZQaU1BeTZRblFOeEpkbEo3dXQzeXhJSzEyb3NLc0RtQ1oyTW1nPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZMjZmMmJnM0wzTEx3L1AxUWFGQ2tCRm9qbnhMZlR6OUV4cHdsR1BXdGk0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndIZkYrWXJFVFdZOTQ4Y3FQSWkvV0FJRmJYRmNja0tQTGVwYmNLTkg4Mms9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitmemtxdTZkOTJxa3BwOEp4bElCYzl5MHlmUEE0SlRPK2dSR2hxbCtIQ2c9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRU9zcFp0L1JzdmZFeXozMWhrVU53SG1CaGx0ckxaYmptY1Q4eFM4d3FWVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUJRTnBkYWoxQmhqVWhwTDVrZURIWHFNL2VNYmNCQy9HTmpENm9rbnZ5QT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImR1aVZmNXpBb2ZPMDlwejdYU0RESHZEYmFTNytvblZCOHVsU1JsaDVGdFpFU3BLYVd4cTJSVmhMenlOcG5sWVptSDBQeFM0N3lrNGdYbTU4V1dUZ0FRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTQ3LCJhZHZTZWNyZXRLZXkiOiJlR0xxTkpOOXZvbkVZWnZqQTVvMEdHOUpBZ0svY05PSzhUdGU5VndsYTNNPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkxODEyOTkwMjQ4NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBNURCOUM4NTEyQzZDMjNCODJDRUNDRDcwQkMwM0QzQSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzY5MDI1NDE1fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MTgxMjk5MDI0ODRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQTU4Nzk2RUNCNTE2NkZEMjkwMTUyMDNBQ0YyOUI1OEEifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc2OTAyNTQxNn0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTE4MTI5OTAyNDg0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkE1MzNDMDUwNTZCRjM3NDgyNUI3ODhBN0RBODREMzM1In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NjkwMjU0MTZ9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkxODEyOTkwMjQ4NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBNTZGRjMxNkJBODdDRjFDNjlGRjc2M0Y3NDQ1RjVEMyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzY5MDI1NDE3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MTgxMjk5MDI0ODRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQTVDREY5N0U1MUNCMjQ3QzMxNDBCQzM5MzJENDVFNDMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc2OTAyNTQxOX0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTE4MTI5OTAyNDg0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkE1OUY1NjlCRURGNEUwREM1MEExRDkyNTREMTUzQkVDIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NjkwMjU0MjB9XSwibmV4dFByZUtleUlkIjo4MTMsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo4MTMsImFjY291bnRTeW5jQ291bnRlciI6MiwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiWVVQUkFERVYiLCJtZSI6eyJpZCI6IjkxODEyOTkwMjQ4NDo5QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IlJlbWl4IiwibGlkIjoiMjMzOTE3MzQwNzQ1OTQyOjlAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNJcVh1YkFIRVByZXhNc0dHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJ1M0s3RHo4TmVaQTRUeGIyK3N2M3RvVnZMd3ErK25zd3JoK2NvdDErVkNzPSIsImFjY291bnRTaWduYXR1cmUiOiJrVmQyVmYzb0dwamlJbmdOcit5azlRckdhSGlzODdBaDZ3dGZ6bjBZQXlvUGJTdm1WVmR5a0hBeG5kd1l3WGxoU255NGFmUVZ2SjhCN1ZrV0RXbW5BZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiOTJLdTIxUmN2NmFBQlJsVWRWM2RtZ1lWOUs3aUxIcFlEazdTR1FhdTArcVBXVzd2R1VVR1h1M2dhT2JKT3R0NkRsbXJwS01yTUpta292MzlyOVg1QkE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5MTgxMjk5MDI0ODQ6OUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJidHl1dzgvRFhtUU9FOFc5dnJMOTdhRmJ5OEt2dnA3TUs0Zm5LTGRmbFFyIn19XSwicGxhdGZvcm0iOiJzbWJhIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQWtJQ0FnUyJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NjkwMjU0MTUsImxhc3RQcm9wSGFzaCI6IjRaUlA2UyIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRS84In0=
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
